### PR TITLE
#184 - Fix new-branch script

### PR DESCRIPTION
**Pull request by gregturn**
* Set it up to work NOT in offline mode
* Rename it to drop the .sh suffix. That way, we can change its language in the future without user having to know.

### CODE REVIEW

**Comment by olivergierke** [comment]
What have been the issues with running this in offline mode. I've always enjoyed the fact, that I can run this script without it trying to reach out to the internet. Shall we maybe add a parameter to the script that allows to run this in both modes?

**Comment by gregturn** [comment]
I suppose that's possible. I wanted the script to run no matter the situation, and reaching out the internet didn't bug me. The one time I could see that getting in your way is if you want to create a new branch and you are on a train with no internet. So, I can work on a such a flag.

**Comment by gregturn** [comment]
@olivergierke git messed up my commit message because of the "#" prefix on the top line. Grrr.

**Comment by olivergierke** [comment]
Merged. I removed the additional `--offline` flag as the offline mode doesn't make too much sense on a second though: either you have all the required dependencies already, then even if online, the build wouldn't reach out to the internet. If you don't have all dependencies, running offline will just fail anyway.

**Pull request closed without merging**
